name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Usa Gradle instalado por la acción para generar el wrapper
      - name: Generate Gradle Wrapper
        uses: gradle/gradle-build-action@v2
        with:
          arguments: wrapper --gradle-version 8.7

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew || true

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Presupuestador-debug-apk
          path: app/build/outputs/apk/debug/*.apk
